spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true      
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    default-encoding: UTF-8
    protocol: smtp
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    check-template-location: false    
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/pictgram
#    username: pictgram
#    password: password 
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
          github:
            clientId: ${github.client.id}
            clientSecret: ${github.client.secret}  
            
image:
   local: false 
   
cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
      
onesignal:
   id: ${6fcb22b4-087b-4c29-8b60-65ff2c8cd966}    
googlemap:
  key: ${googlemap.key}    
