spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true      
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pictgram
    username: pictgram
    password: password 
      
image:
  local: false
cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-1
    
    
     